name: Tests
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set environment variables from .env
        uses: xom9ikk/dotenv@v2.3.0
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run tests
        run: go test -v ./...
        env:
          VAULT_ACC: '1'
          TEST_SCALR_HOSTNAME: ${{ secrets.TEST_SCALR_HOSTNAME }}
          TEST_SCALR_ACCOUNT_ID: ${{ secrets.TEST_SCALR_ACCOUNT_ID }}
          TEST_SCALR_TOKEN: ${{ secrets.TEST_SCALR_TOKEN }}